CREATE TABLE public.aqe_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_key VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    db_type VARCHAR(20) NOT NULL,
    host_encrypted TEXT NOT NULL,
    port_encrypted TEXT NOT NULL,
    database_name_encrypted TEXT NOT NULL,
    username_encrypted TEXT NOT NULL,
    password_encrypted TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_aqe_connection_connection_key UNIQUE (connection_key)
);
